// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxLJKqbRORDFp-pVgO2ZOcAee7LboTLlg',
    appId: '1:1015827045951:web:bd6e2b5e0ff49711c9228a',
    messagingSenderId: '1015827045951',
    projectId: 'meetingbuds',
    authDomain: 'meetingbuds.firebaseapp.com',
    storageBucket: 'meetingbuds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSyALuviKUAyYtCzeV9giZKT3kCnRyIA',
    appId: '1:1015827045951:android:dc502d09c8d0baa8c9228a',
    messagingSenderId: '1015827045951',
    projectId: 'meetingbuds',
    storageBucket: 'meetingbuds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyB1E-bJxw3wnuzq7w8leRAzQieGvZgs',
    appId: '1:1015827045951:ios:ed8f2974902f2cfdc9228a',
    messagingSenderId: '1015827045951',
    projectId: 'meetingbuds',
    storageBucket: 'meetingbuds.firebasestorage.app',
    iosBundleId: 'com.example.meetBuddies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyB1E-bJxw3wnuzq7w8leRAzQieGvZgs',
    appId: '1:1015827045951:ios:ed8f2974902f2cfdc9228a',
    messagingSenderId: '1015827045951',
    projectId: 'meetingbuds',
    storageBucket: 'meetingbuds.firebasestorage.app',
    iosBundleId: 'com.example.meetBuddies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxLJKqbRORDFp-pVgO2ZOcAee7LboTLlg',
    appId: '1:1015827045951:web:a926a5c1b409cd9bc9228a',
    messagingSenderId: '1015827045951',
    projectId: 'meetingbuds',
    authDomain: 'meetingbuds.firebaseapp.com',
    storageBucket: 'meetingbuds.firebasestorage.app',
  );
}
